apiVersion: v1
kind: Pod
metadata:
  name: calculator-pod
  labels:
    component: calculator
spec:
  containers:
    - name: calculator
      image: aswwsa/flask_micro__k8s_calculator
      ports:
        - containerPort: 5000
